<?php

namespace CorinneBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetRepository extends EntityRepository
{
}
